[tool.poetry]
name = "iwanna"
version = "1.0.0"
description = "CLI tool to get shell command suggestions using GPT-4 to help you perform your action."
authors = ["Carl Oscar Aaro <hello@carloscar.com>"]
homepage = "https://github.com/kalaspuff/iwanna"
repository = "https://github.com/kalaspuff/iwanna"
keywords = ["cli tool", "shell suggestion", "gpt-4", "openai shell assistant", "ai assistant"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: System :: Shells",
    "Topic :: Utilities",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License"
]

[tool.poetry.dependencies]
python = "^3.8"
openai = "^0.27.2"
termcolor = "^2.2.0"
progress = "^1.6"
tomli = "^2.0.1"

[tool.poetry.group.dev.dependencies]
flake8 = ">=3.8.4"
flake8-isort = ">=4.0.0"
flake8-black = ">=0.2.0"
flake8-pyproject = ">=1.1.0"
pytest = ">=6.1.0"
pytest-cov = ">=2.10.0"
codecov = ">=2.1.10"
isort = ">=5.12.0"
black = ">=23.1.0"
mypy = ">=0.800"
python-dotenv = ">=1.0.0"
poetry-dotenv-plugin = ">=0.1.0"
types-termcolor = ">=1.1.6.1"

[tool.poetry.scripts]
iwanna = "iwanna.app:cli_entrypoint"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target_version = ["py38", "py39", "py310", "py311"]
include = '\.pyi?$'
exclude = '\.eggs/|\.egg-info/|\.git/|\.github/|\.mypy_cache/|\.venv/|\.pytest_cache/|\.vscode/|__pycache__/|build/|dist/|setup\.py'

[tool.isort]
profile = "black"
line_length = 120
src_paths = ["iwanna"]
known_first_party = "iwanna"
skip = [".mypy_cache", ".pytest_cache", "__pycache__", "iwanna.egg-info", ".eggs", ".git", ".venv", ".vscode", "build", "dist", "tmp"]

[tool.mypy]
pretty = true
files = ["$MYPY_CONFIG_FILE_DIR/iwanna"]
ignore_missing_imports = true
show_error_codes = true
no_implicit_reexport = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
local_partial_types = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true

[tool.flake8]
ignore = ["E203", "E501", "W503"]
exclude = ["iwanna.egg-info", ".git", ".mypy_cache", ".pytest_cache", ".venv", ".vscode", "__pycache__", "build", "dist", "tmp"]
